### ISSUE TITLE
hgetall returns Array

### ISSUE THREAD

**Issue by Thor77** [stefanwille/crystal-redis#4]
`hgetall` should return a Hash instead
(referring to [redis-documentation](http://redis.io/topics/data-types-intro#hashes))

**Comment by stefanwille** [comment]
Yes, would be friendlier.

**Comment by vladfaust** [comment]
Bumping. Why isn't it still merged with master?

**Comment by stefanwille** [comment]
This is a bigger issue: Redis represents hashes as arrays in multiple places, and this PR addresses only one spot. By returning a proper hash in only one place, the api becomes inconsistent. I'd like to change the affected methods all at once. But doing this without a lot of code duplication is difficult. That's why I didn't merge this PR.

**Comment by tachyons** [comment]
@robacarp  I have addressed store_hash here https://github.com/stefanwille/crystal-redis/pull/113 to avoid multiple redis queries. retrieve_hash can be simplified to 
```crystal
  def retrieve_hash(name : String) : Hash(String, String)
      data = hgetall(name)
      data.each_slice(2).to_h
    end
```
