### ISSUE TITLE
Improve memory benchmark?

### ISSUE THREAD

**Issue by proyb6** [stefanwille/crystal-redis#71]
It has been nearly 3 years and I see Go and Crystal have improved that they are so close.

On macOS Mojave
https://github.com/stefanwille/redis-client-benchmarks

Crystal 0.26.1
Time 2.25s
Memory 130MB

Go 1.11
Time 2.58s
Memory <12MB

I wonder if Crystal could reduce memory usage?

**Comment by stefanwille** [comment]
Hi @proyb6! When I built this shard, I thought the main reason why people use Redis over an RDBMS is performance, and therefore the shard should perform well. I needed something to measure this shard against others libraries so that I knew where I stood. As such I built it as a microbenchmark - it is not representative of a programming language. In this sense it would fun to see updated numbers, but it would really be just a fun thing. If one day I feel like it will do it, but don't wait for it.
